# Generated by Django 4.2.3 on 2023-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='is_viewed',
            field=models.BooleanField(null=True),
        ),
    ]
