# Generated by Django 4.2.3 on 2023-07-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0002_alter_generatedimage_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='is_viewed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='selected_image_id',
            field=models.IntegerField(null=True),
        ),
    ]
