# Generated by Django 4.2.3 on 2023-07-07 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0003_alter_generatedimage_is_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='selected_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='taskId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
