# Generated by Django 4.2.3 on 2023-07-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0004_generatedimage_created_at_generatedimage_selected_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedimage',
            old_name='taskId',
            new_name='task_id',
        ),
    ]
