# Generated by Django 4.2.3 on 2023-07-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0005_rename_taskid_generatedimage_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='selected_image_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='task_id',
            field=models.CharField(null=True),
        ),
    ]
