# Generated by Django 4.2.3 on 2023-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0006_alter_generatedimage_is_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image_id', models.CharField(max_length=255)),
                ('image_type', models.CharField(choices=[('main', 'Main'), ('splitted', 'Splitted'), ('removed_background', 'Removed Background'), ('up_scaled', 'Up Scaled')], max_length=20)),
                ('image_url', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
