# Generated by Django 4.2.3 on 2023-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image_generator', '0008_alter_generatedimage_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimageitem',
            name='image_type',
            field=models.CharField(choices=[('main', 'Main'), ('splitted', 'Splitted'), ('removed_background', 'Removed Background'), ('up_scaled', 'Up Scaled')], max_length=20, null=True),
        ),
    ]
